config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#top'
  get 'home/about'
  get 'searches/users' => 'searches#search', as: 'search_user'
  get 'searches/books' => 'searches#search_book', as: 'search_book'
  resources :users,only: [:show,:index,:edit,:update]
  resources :relationships, only: [:create, :destroy]
  get 'user/:id/follows' => 'relationships#following', as: 'follows'
  get 'user/:id/followers' => 'relationships#follower', as: 'followers'
  resources :books do
  	resources :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  attachment :profile_image, destroy: false
    #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence: true,
            length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50 }

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def self.search(method,word)
    if method == "forward_match"
      @users = User.where("name LIKE?","#{word}%")
    elsif method == "backward_match"
      @users = User.where("name LIKE?","%#{word}")
    elsif method == "perfect_match"
      @users = User.where("#{word}")
    elsif method == "partial_match"
      @users = User.where("name LIKE?","%#{word}")
    else
      @users = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
    @user = User.find(params[:id])
    flash.now[:notice] = 'update error'
  		render "edit"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_button.html.erb
<% unless current_user == user%>
	<% if current_user.following?(user) %>
		<%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
			<%= hidden_field_tag :follow_id, user.id %>
			<%= f.submit 'フォローを外す', class: 'btn btn-danger btn-block' %>
		<% end %>
	<% else %>
		<%= form_for(current_user.relationships.build) do |f| %>
			<%= hidden_field_tag :follow_id, user.id %>
			<%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %>
		<% end %>
	<% end %>
<% end %>

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
</table>

<div class="row">
	<% if user == current_user %>
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	<% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<%= render 'layouts/search' %>
			<h2>Users</h2>
			<!--users一覧 -->
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name%></td>
						<td>
							フォロー数　<%= user.followings.count %>
						</td>
						<td>
							フォロワー数　<%= user.followers.count %>
						</td>

						<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
						<td>
							<%= render 'users/follow_button', user: user %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
				<%= render 'users/profile', user: @user %>
				<p>
					<li>
						フォロー数　<%= link_to @user.followings.count, follows_path(@user) %>
					</li>
					<li>
						フォロワー数　<%= link_to @user.followers.count, followers_path(@user) %>
					</li>
			    </p>
				<%= render 'users/follow_button', user: @user %>
			<!--同コントローラーのviewで表示ならusersは省略可 -->

			<h2>New book</h2>
				<%= render 'books/newform', book: @book %>
		</div>

			<div class="col-xs-9">
			<%= render 'layouts/search' %>
			<h2>Books</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to (book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
	<!--books一覧 -->

		</div>
	</div>
</div>