config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#top'
  get 'home/about'
  get 'searches/users' => 'searches#search', as: 'search_user'
  get 'searches/books' => 'searches#search_book', as: 'search_book'
  resources :users,only: [:show,:index,:edit,:update]
  resources :relationships, only: [:create, :destroy]
  get 'user/:id/follows' => 'relationships#following', as: 'follows'
  get 'user/:id/followers' => 'relationships#follower', as: 'followers'
  resources :books do
  	resources :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def self.search(method,word)
	    if method == "forward_match"
	      @books = Book.where("title LIKE?","#{word}%")
	    elsif method == "backward_match"
	      @books = Book.where("title LIKE?","%#{word}")
	    elsif method == "perfect_match"
	      @books = Book.where("#{word}")
	    elsif method == "partial_match"
	      @books = Book.where("title LIKE?","%#{word}")
	    else
	      @books = Book.all
	    end
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
    @user = User.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
      flash.now[:notice] = "create error"
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
    if current_user.id != @book.user_id
        redirect_to books_path
    end
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
    @book = Book.find(params[:id])
    flash.now[:notice] = "edit error"
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<%= render 'layouts/search' %>
			<h2>Books index</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
						<tr>
							<td>
								<%= link_to(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
								<% end %>
							</td>
							<td>
								<%= link_to book.title, book, class: "book_#{book.id}" %>
							</td>
							<td>
								<%= book.body %>
							</td>
							<td>
								<% if book.favorited_by?(current_user) %>
									  <%= link_to book_favorite_path(book, current_user), method: :delete do %>
									    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
									    <%= book.favorites.count %> いいね
									  <% end %>
									<% else %>
										  <%= link_to book_favorites_path(book), method: :post do %>
										    <i class="fa fa-heart-o" aria-hidden="true"></i>
										    <%= book.favorites.count %> いいね
									      <% end %>
								<% end %>
							</td>
							<td>
								<%= link_to "コメント数 #{book.book_comments.count}", book_path(book.id) %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>

			<!--books一覧 -->


		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: Book.new, user: current_user %>

		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>

			<table class="table">
					<tr>
						<td>
							<%= link_to (@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
							<%= @book.user.name %>
							<% end %>
						</td>
						<td>
							<%= link_to @book.title, @book %>
						</td>
						<td>
							<%= @book.body %>
						</td>

						<td>
							<% if @book.favorited_by?(current_user) %>
								  <%= link_to book_favorite_path(@book), method: :delete do %>
								    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
								    <%= @book.favorites.count %> いいね
								  <% end %>
								<% else %>
									  <%= link_to book_favorites_path(@book), method: :post do %>
									    <i class="fa fa-heart-o" aria-hidden="true"></i>
									    <%= @book.favorites.count %> いいね
								      <% end %>
							<% end %>
						</td>

						<td>
							コメント数<%=  @book.book_comments.count %>
						</td>

						<% if @book.user == current_user %>
						<td>
							<%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %>

						</td>
						<td>
							<%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %>
						</td>
						<% end %>
					</tr>
				</table>
				<ol>
				  <% @book.book_comments.each do |book_comment| %>
				    <li class="comment">
				      <div class="comment-body bb">
				        <div class="comment-avatar">
				          <div class="avatar">
				            <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %>
				            <br>
				          </div>
				        </div>
				        <div class="comment-text">
				          <div class="comment-author clearfix">
				            <a href="#" class="link-author"><%= book_comment.user.name %></a>
				            <span class="comment-meta">
				              <span class="comment-date"><%= book_comment.created_at.strftime('%Y/%m/%d') %></span>
				            </span>
				            <div class="comment-entry">
				          	<%= book_comment.comment %>
				          </div>

				          <% if book_comment.user == current_user %>
				          <div>
				          	<%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
				          </div>
				          <% end %>
				        </div>
				      </div>
				    </li>
				  <% end %>
				</ol>
				<%= form_for [@book, @book_comment] do |f| %>
					<%= f.text_area :comment  %>
					<%= f.submit "送信" %>
				<% end %>
		</div>
	</div>
</div>